### ISSUE TITLE
`bootc install to-filesystem --source-imref` not supported yet on quay.io/centos-bootc/centos-bootc:stream9

### ISSUE THREAD

**Issue by mvo5** [containers/bootc#360]
When trying to build a centos stream9 image with the new experimental bootc-image-builder that uses `bootc instlal to-filesystem` it seems the quay.io/centos-bootc/centos-bootc:stream9 needs a newer bootc version:
```
...
error: unexpected argument '--source-imgref' found

  tip: a similar argument exists: '--target-imgref'

Usage: bootc install to-filesystem <--target-transport <TARGET_TRANSPORT>|--target-imgref <TARGET_IMGREF>|--target-no-signature-verification|--enforce-container-sigpolicy|--target-ostree-remote <TARGET_OSTREE_REMOTE>|--skip-fetch-check> <ROOT_PATH>

For more information, try '--help'.
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 72, in <module>
    r = main(args["inputs"], args["paths"])
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 59, in main
    subprocess.run(
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bootc', 'install', 'to-filesystem', '--source-imgref', 'dir:/tmp/tmpnaize2h0/image', '--skip-fetch-check', '--generic-image', '/run/osbuild/mounts']' returned non-zero exit status 2.
```

The `quay.io/centos-bootc/centos-bootc-dev:stream9 ` works though so this is not a blocker for us :)

**Comment by cgwalters** [comment]
Yeah, c9s composes can have long arbitrary delays.  This will be fixed by https://github.com/CentOS/centos-bootc/pull/357 (I'd recommend filing issues related to specific base images in their respective repositories) in general.
